export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const REDUCE_ITEM_QUANTITY = "REDUCE_ITEM_QUANTITY";
export const DEFAULT_CATEGORY_STATE = "DEFAULT_CATEGORY_STATE";
export const DEFAULT_SHOP_STATE = "DEFAULT_SHOP_STATE";